name: Dry-Run Release
on:
  pull_request:

jobs:
  lint-commits:
    name: Lint PR commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@b948419dd99f3fd78a6548d48f94e3df7f6bf3ed # v6

  test-release:
    name: Dry-run semantic-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - name: Checkout branch
        # Pretend to semantic-release that the PR result is eligible for
        # building releases because --dry-run still filters for configured
        # branches.
        run: git checkout -b main
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: npm install
      - name: Dry-run release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        # We need to convince semantic-release to not pick up some
        # configuration from the CI environment by removing the variable that
        # is used for CI detection.
        run: unset GITHUB_ACTIONS && npx semantic-release --dry-run --ci false
