openapi: "3.0.3"
info:
  title: "Modelix Maven Connector"
  version: "1.0.0"
servers:
  - url: '/api/modelix/maven-connector'
    description: Makes artifacts from maven repositories available to other services
tags:
  - name: MavenConnector
paths:
  /:
    get:
      operationId: getMavenConnectorConfig
      tags: [MavenConnector]
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MavenConnectorConfig'
  /repositories/:
    get:
      operationId: listMavenRepositories
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MavenRepositoryList'
  /repositories/{repositoryId}:
    get:
      operationId: getMavenRepository
      tags: [MavenConnector]
      parameters:
        - name: repositoryId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MavenRepository'
    put:
      operationId: updateMavenRepository
      tags: [MavenConnector]
      parameters:
        - name: repositoryId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MavenRepository'
      responses:
        "200":
          description: OK
    delete:
      operationId: deleteMavenRepository
      tags: [MavenConnector]
      parameters:
        - name: repositoryId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
  /artifacts/:
    get:
      operationId: listMavenArtifacts
      tags: [MavenConnector]
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MavenArtifactList'
components:
  schemas:
    MavenConnectorConfig:
      type: object
      required: [repositories, artifacts]
      properties:
        repositories:
          type: array
          items:
            $ref: '#/components/schemas/MavenRepository'
        artifacts:
          type: array
          items:
            $ref: '#/components/schemas/MavenArtifact'
    MavenRepositoryList:
      type: object
      required: [repositories]
      properties:
        repositories:
          type: array
          items:
            $ref: '#/components/schemas/MavenRepository'
    MavenRepository:
      type: object
      required: [id, url]
      properties:
        id:
          type: string
          nullable: false
        url:
          type: string
          nullable: false
    MavenArtifactList:
      type: object
      required: [artifacts]
      properties:
        artifacts:
          type: array
          items:
            $ref: '#/components/schemas/MavenArtifact'
    MavenArtifact:
      type: object
      required: [groupId, artifactId]
      properties:
        groupId:
          type: string
          nullable: false
        artifactId:
          type: string
          nullable: false
        version:
          type: string
          nullable: true

  securitySchemes:
    modelixJwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - modelixJwtAuth: []
